const data = [
    { id: '1', marca: 'Honda', titulo: 'Honda Civic Type-R', categoria: 'importados', precio: '6,458,000', detalle: 'Motor 4.0 Turbo de 330 CV', descripcion: 'El Mazda RX-7 es un automóvil deportivo producido por el fabricante japonés Mazda Motor Corporation  entre los años 1978 y 2002. ', img: 'https://cdn.autobild.es/sites/navi.axelspringer.es/public/styles/855/public/media/image/2020/06/increible-historia-honda-civic-type-r-1978221.jpg?itok=QtFfau-y' },
    { id: '2', marca: 'Mazda', titulo: ' Mazda RX-7', categoria: 'importados', precio: '7,458,000', detalle: 'Motor 3.0 Turbo de 340 CV', descripcion: 'El Mazda RX-7 es un automóvil deportivo producido por el fabricante japonés Mazda Motor Corporation  entre los años 1978 y 2002. ', img: 'https://cdn.autobild.es/sites/navi.axelspringer.es/public/styles/1200/public/media/image/2018/06/mazda-rx-7-fb_3.jpg?itok=VpPr4SZx' },
    { id: '3', marca: 'Toyota', titulo: 'Toyota Supra', categoria: 'nacionales', precio: '10,458,000', detalle: 'Motor 3.0 Turbo de 375 CV', descripcion: 'El Mazda RX-7 es un automóvil deportivo producido por el fabricante japonés Mazda Motor Corporation  entre los años 1978 y 2002. ', img: 'https://cdn.autobild.es/sites/navi.axelspringer.es/public/styles/855/public/media/image/2019/11/toyota-supra-ac-schnitzer_7.jpg?itok=p7DI7qM-' },
    { id: '4', marca: 'Toyota', titulo: 'Toyota Prius', categoria: 'nacionales', precio: '2,458,000', detalle: 'Motor 2.5 Turbo de 360 CV', descripcion: 'El Mazda RX-7 es un automóvil deportivo producido por el fabricante japonés Mazda Motor Corporation  entre los años 1978 y 2002. ', img: 'https://cdn.autobild.es/sites/navi.axelspringer.es/public/styles/855/public/media/image/2020/08/aprende-autobildinyeccionprius-2020927.jpg?itok=dGO1JuEv' }

]


export default data;